//! oracle — the CONTENT ORACLE, now driven by the engine's built-in recorder
//! instead of bespoke per-game tallying. The bootstrap (spawn the world) is the
//! only world-specific code; `print_manifest` reads ONLY engine tallies
//! (action_tally / event_tally / action_names / peak / avg_count), so the exact
//! same reporter works for tavern, ferry, metropolis, or any future world file.

use std::collections::BTreeMap;

use owos_core::engine::{Broadcast, EntityId, Reducer, Rollup, World};

#[derive(serde::Deserialize)]
struct EffDef { op: String, #[serde(default)] stat: String, #[serde(default)] expr: String }
#[derive(serde::Deserialize)]
struct RuleDef { on: String, set: String, expr: String }
#[derive(serde::Deserialize)]
struct ActDef { on: String, name: String, score: String, effects: Vec<EffDef> }
#[derive(serde::Deserialize)]
struct EventDef { on: String, when: String, label: String, #[serde(rename = "do")] do_: Vec<EffDef> }
#[derive(serde::Deserialize)]
struct GenDef { on: String, spawn: String, count: String, #[serde(default)] child_stats: BTreeMap<String, String> }
#[derive(serde::Deserialize)]
struct RollDef { parent: String, child_stat: String, parent_stat: String, reduce: String }
#[derive(serde::Deserialize)]
struct BcastDef { parent_stat: String, child_stat: String, gain: f32 }
#[derive(serde::Deserialize)]
struct Def {
    rules: Vec<RuleDef>,
    #[serde(default)] coarse_rules: Vec<RuleDef>,
    actions: Vec<ActDef>,
    events: Vec<EventDef>,
    generators: Vec<GenDef>,
    rollups: Vec<RollDef>,
    broadcasts: Vec<BcastDef>,
}

fn effs(v: &[EffDef]) -> Vec<(String, String, String)> {
    v.iter().map(|e| (e.op.clone(), e.stat.clone(), e.expr.clone())).collect()
}
fn reducer(s: &str) -> Reducer {
    match s { "sum" => Reducer::Sum, "max" => Reducer::Max, "min" => Reducer::Min, "frac_above" => Reducer::FracAbove(0.5), _ => Reducer::Mean }
}
fn wire(w: &mut World, def: &Def) {
    for r in &def.rules { w.add_rule(&r.on, &r.set, &r.expr).unwrap(); }
    for r in &def.coarse_rules { w.add_coarse_rule(&r.on, &r.set, &r.expr).unwrap(); }
    for a in &def.actions { w.add_data_action(&a.on, &a.name, &a.score, effs(&a.effects)).unwrap(); }
    for e in &def.events { w.add_event(&e.on, &e.when, effs(&e.do_), &e.label).unwrap(); }
    for g in &def.generators {
        let cs: Vec<(String, String)> = g.child_stats.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
        w.add_generator(&g.on, &g.spawn, &g.count, cs).unwrap();
    }
    for r in &def.rollups {
        w.add_rollup(Rollup { parent_kind: r.parent.clone(), child_stat: r.child_stat.clone(), parent_stat: r.parent_stat.clone(), reducer: reducer(&r.reduce), drain: false });
    }
    for b in &def.broadcasts {
        w.add_broadcast(Broadcast { parent_kind: String::new(), parent_stat: b.parent_stat.clone(), child_stat: b.child_stat.clone(), gain: b.gain });
    }
}

fn reveal_all(w: &mut World, id: EntityId, cap: usize) {
    if w.entities.len() > cap { return; }
    w.reveal(id);
    for c in w.children(id) { reveal_all(w, c, cap); }
}

// ===== the GENERIC reporter — reads only engine tallies, knows no game =====
fn print_manifest(w: &World, days: u32, watched: &[&str]) {
    println!("══════════ CONTENT MANIFEST · generated by the engine recorder ══════════");
    println!("Simulated {days} in-world days. Nothing below was tallied by hand — the engine recorded it.\n");

    // Crowd / spawn budget from watched headcounts.
    println!("POPULATION / SPAWN BUDGET:");
    for &k in watched {
        println!("   {k}: peak {} live at once, avg {:.0} — size your pools/render budget to the peak.", w.peak(k), w.avg_count(k));
    }
    println!();

    // What agents actually DID — every action is a state/animation to build.
    let tally = w.action_tally();
    let total: u64 = tally.values().sum();
    let mut ranked: Vec<(&String, &u64)> = tally.iter().collect();
    ranked.sort_by(|a, b| b.1.cmp(a.1));
    let top = ranked.first().map(|(_, c)| **c).unwrap_or(1);
    println!("BEHAVIORS EXERCISED  ({} distinct, {} total acts — each = content to build, ranked):", ranked.len(), total);
    for (name, count) in &ranked {
        let n = ((**count as f64 / top as f64) * 30.0).round() as usize;
        let bar = if n == 0 { "▏".to_string() } else { "█".repeat(n) };
        let pct = **count as f64 / total as f64 * 100.0;
        println!("   {name:<22} {bar} {count} ({pct:.1}%)");
    }
    println!();

    // Defined-but-unused — dead / over-scoped / needs-a-driver content.
    let mut dead: Vec<String> = Vec::new();
    for (kind, name) in w.action_names() {
        let key = format!("{kind}:{name}");
        let c = tally.get(&key).copied().unwrap_or(0);
        if (c as f64) / (total.max(1) as f64) < 0.003 {
            dead.push(format!("{key} ({c}×)"));
        }
    }
    println!("⚠ DEFINED BUT (almost) NEVER EXERCISED — cut, cheapen, or it needs a driver:");
    if dead.is_empty() { println!("   (none — every authored action earned its place)"); }
    for d in &dead { println!("   {d}"); }
    println!();

    // Set-pieces / events — including the ones that never fired.
    println!("SET-PIECES / EVENTS:");
    for (label, count) in w.event_tally() {
        if *count == 0 {
            println!("   ⚠ \"{label}\" — DEFINED but NEVER fired in {days} days (thresholds too high, or cut it)");
        } else {
            println!("   \"{label}\" — fired {count}× → 1 set-piece, prioritize to match");
        }
    }
}

fn main() {
    let text = std::fs::read_to_string("worlds/metropolis.json").expect("read worlds/metropolis.json");
    let def: Def = serde_json::from_str(&text).expect("parse metropolis.json");

    // --- world-specific bootstrap (the ONLY non-generic part) ---
    let mut w = World::new(42);
    wire(&mut w, &def);
    let metro = w.spawn("metro", "MERIDIAN", w.root);
    for (k, v) in [("population", 1.0), ("rent_index", 1.0), ("wealth", 0.5), ("opportunity", 0.6), ("unrest", 0.4), ("crime", 0.3)] {
        w.set(metro, k, v);
    }
    reveal_all(&mut w, metro, 5000); // a modest, fully-live slice of the city

    // --- generic: turn the recorder on and just live a while ---
    let days = 24;
    w.record(true);
    w.watch("person");
    for _ in 0..days { w.step(); }

    println!("(city bootstrapped: {} live people across the opened districts)\n", w.by_kind("person").len());
    print_manifest(&w, days, &["person"]);
}
